#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA2C794A986419D8A (tstellar@redhat.com)
#
%define keepstatic 1
Name     : llvm8
Version  : 8.0.1
Release  : 12
URL      : https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz
Source0  : https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz
Source1  : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v8.0.1-1/SPIRV-8.0.1.1.tar.gz
Source2  : https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/cfe-8.0.1.src.tar.xz
Source3  : https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz.sig
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT NCSA
Requires: llvm8-bin = %{version}-%{release}
Requires: llvm8-lib = %{version}-%{release}
Requires: llvm8-license = %{version}-%{release}
Requires: llvm8-extras = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : Z3-dev
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : libffi-dev
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : llvm
BuildRequires : llvm9
BuildRequires : ncurses-dev
BuildRequires : python3-dev
BuildRequires : subversion
BuildRequires : valgrind-dev
BuildRequires : zlib-dev
Patch1: python2-shebangs.patch
Patch2: llvm-0001-CMake-Split-static-library-exports-into-their-own-ex.patch
Patch3: llvm-0002-Improve-physical-core-count-detection.patch
Patch4: llvm-0003-Produce-a-normally-versioned-libLLVM.patch
Patch5: llvm-0004-NFC-include-cstdint-string-prior-to-using-uint8_t-st.patch
Patch6: clang-0001-Allow-building-split-libclang-libraries-with-unified.patch
Patch7: clang-0002-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch
Patch8: clang-0003-Make-Clang-default-to-Westmere-on-Clear-Linux.patch
Patch9: clang-0004-Change-type-of-block-pointer-for-OpenCL.patch
Patch10: clang-0005-Simplify-LLVM-IR-generated-for-OpenCL-blocks.patch
Patch11: clang-0006-Fix-assertion-due-to-blocks.patch
Patch12: clang-0007-Add-the-LLVM-major-version-number-to-the-Gold-LTO-pl.patch
Patch13: fma.patch
Patch14: clang-gcc.patch

%description
See docs/CMake.html for instructions on how to build LLVM with CMake.

%package bin
Summary: bin components for the llvm8 package.
Group: Binaries
Requires: llvm8-license = %{version}-%{release}

%description bin
bin components for the llvm8 package.


%package extras
Summary: extras components for the llvm8 package.
Group: Default

%description extras
extras components for the llvm8 package.


%package extras-libllvm
Summary: extras-libllvm components for the llvm8 package.
Group: Default

%description extras-libllvm
extras-libllvm components for the llvm8 package.


%package lib
Summary: lib components for the llvm8 package.
Group: Libraries
Requires: llvm8-license = %{version}-%{release}

%description lib
lib components for the llvm8 package.


%package license
Summary: license components for the llvm8 package.
Group: Default

%description license
license components for the llvm8 package.


%prep
%setup -q -n llvm-8.0.1.src
cd %{_builddir}
tar xf %{_sourcedir}/cfe-8.0.1.src.tar.xz
cd %{_builddir}
tar xf %{_sourcedir}/SPIRV-8.0.1.1.tar.gz
cd %{_builddir}/llvm-8.0.1.src
mkdir -p tools/clang
cp -r %{_builddir}/cfe-8.0.1.src/* %{_builddir}/llvm-8.0.1.src/tools/clang
mkdir -p projects/SPIRV
cp -r %{_builddir}/SPIRV-LLVM-Translator-8.0.1-1/* %{_builddir}/llvm-8.0.1.src/projects/SPIRV
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589822334
unset LD_AS_NEEDED
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_BUILD_SHARED_LIBS:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_CXX1Y=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_LIBCXX:BOOL=OFF \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_INSTALL_UTILS:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
-DCLANG_TOOL_SCAN_VIEW_BUILD:BOOL=OFF \
-DCLANG_TOOL_SCAN_BUILD_BUILD:BOOL=OFF \
-DLLVM_TOOL_OPT_VIEWER_BUILD:BOOL=OFF \
-DLLVM_INSTALL_UTILS:BOOL=OFF \
-DCMAKE_C_COMPILER=clang-9 \
-DCMAKE_CXX_COMPILER=clang++-9
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make test

%install
export SOURCE_DATE_EPOCH=1589822334
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvm8
cp %{_builddir}/SPIRV-LLVM-Translator-8.0.1-1/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm8/8f178caf2a2d6e6c711a30da69077572df356cf6
cp %{_builddir}/cfe-8.0.1.src/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm8/4b1bf296ce693a6396265c60a2bfc237cae9a14e
cp %{_builddir}/cfe-8.0.1.src/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/llvm8/59d395cdb2e7a9940a56014b5ab7184324ab5cd3
cp %{_builddir}/llvm-8.0.1.src/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm8/e20dfaf19593ba52e55f3fd6e34532193f594fbb
cp %{_builddir}/llvm-8.0.1.src/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm8/c01c212bdf3925189f673e2081b44094023860ea
cp %{_builddir}/llvm-8.0.1.src/tools/msbuild/license.txt %{buildroot}/usr/share/package-licenses/llvm8/59d395cdb2e7a9940a56014b5ab7184324ab5cd3
cp %{_builddir}/llvm-8.0.1.src/utils/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm8/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/llvm-8.0.1.src/utils/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm8/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/llvm-8.0.1.src/utils/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm8/5a2314153eadadc69258a9429104cd11804ea304
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/lib64/libgomp.so
rm -f %{buildroot}/usr/lib64/TestPlugin.so
rm -f %{buildroot}/usr/lib64/cmake/llvm/LLVMStaticExports.cmake
rm -f %{buildroot}/usr/lib64/cmake/llvm/LLVMStaticExports-relwithdebinfo.cmake
rm -f %{buildroot}/usr/lib64/clang/8.0.1/lib/linux/libclang_rt.asan-i386.so
rm -f %{buildroot}/usr/lib64/clang/8.0.1/lib/linux/libclang_rt.scudo-i386.so
rm -f %{buildroot}/usr/lib64/clang/8.0.1/lib/linux/libclang_rt.scudo_minimal-i386.so
rm -f %{buildroot}/usr/lib64/clang/8.0.1/lib/linux/libclang_rt.ubsan_minimal-i386.so
rm -f %{buildroot}/usr/lib64/clang/8.0.1/lib/linux/libclang_rt.ubsan_standalone-i386.so
## install_append content
# Rename the Gold plugin elsewhere, as we're erasing *.so below
mv %{buildroot}/usr/lib64/LLVMgold.so %{buildroot}/usr/lib64/LLVMgold.so.save

# Remove files that should come from the main llvm package
rm -rf %{buildroot}/usr/include
rm -rf %{buildroot}/usr/lib64/*.a
rm -rf %{buildroot}/usr/lib64/*.so
rm -rf %{buildroot}/usr/lib64/cmake
rm -rf %{buildroot}/usr/lib64/pkgconfig
rm -rf %{buildroot}/usr/libexec

mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
rm -rf %{buildroot}/usr/share/*
mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Move the tools to a versioned bin dir and then create symlinks back
pushd %{buildroot}/usr
FULL_VERSION=%{version}
VERSION=${FULL_VERSION%%%%.*}
mv bin lib64/clang/$FULL_VERSION
mkdir bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-$VERSION
done

# Put the LLVM gold plugin back, under the versioned name
mv lib64/LLVMgold.so.save lib64/LLVMgold-$VERSION.so
mkdir -p lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/clang/8.0.1/bin/bugpoint
/usr/lib64/clang/8.0.1/bin/c-index-test
/usr/lib64/clang/8.0.1/bin/clang
/usr/lib64/clang/8.0.1/bin/clang++
/usr/lib64/clang/8.0.1/bin/clang-8
/usr/lib64/clang/8.0.1/bin/clang-check
/usr/lib64/clang/8.0.1/bin/clang-cl
/usr/lib64/clang/8.0.1/bin/clang-cpp
/usr/lib64/clang/8.0.1/bin/clang-extdef-mapping
/usr/lib64/clang/8.0.1/bin/clang-format
/usr/lib64/clang/8.0.1/bin/clang-import-test
/usr/lib64/clang/8.0.1/bin/clang-offload-bundler
/usr/lib64/clang/8.0.1/bin/clang-refactor
/usr/lib64/clang/8.0.1/bin/clang-rename
/usr/lib64/clang/8.0.1/bin/diagtool
/usr/lib64/clang/8.0.1/bin/dsymutil
/usr/lib64/clang/8.0.1/bin/git-clang-format
/usr/lib64/clang/8.0.1/bin/hmaptool
/usr/lib64/clang/8.0.1/bin/llc
/usr/lib64/clang/8.0.1/bin/lli
/usr/lib64/clang/8.0.1/bin/llvm-ar
/usr/lib64/clang/8.0.1/bin/llvm-as
/usr/lib64/clang/8.0.1/bin/llvm-bcanalyzer
/usr/lib64/clang/8.0.1/bin/llvm-c-test
/usr/lib64/clang/8.0.1/bin/llvm-cat
/usr/lib64/clang/8.0.1/bin/llvm-cfi-verify
/usr/lib64/clang/8.0.1/bin/llvm-config
/usr/lib64/clang/8.0.1/bin/llvm-cov
/usr/lib64/clang/8.0.1/bin/llvm-cvtres
/usr/lib64/clang/8.0.1/bin/llvm-cxxdump
/usr/lib64/clang/8.0.1/bin/llvm-cxxfilt
/usr/lib64/clang/8.0.1/bin/llvm-cxxmap
/usr/lib64/clang/8.0.1/bin/llvm-diff
/usr/lib64/clang/8.0.1/bin/llvm-dis
/usr/lib64/clang/8.0.1/bin/llvm-dlltool
/usr/lib64/clang/8.0.1/bin/llvm-dwarfdump
/usr/lib64/clang/8.0.1/bin/llvm-dwp
/usr/lib64/clang/8.0.1/bin/llvm-elfabi
/usr/lib64/clang/8.0.1/bin/llvm-exegesis
/usr/lib64/clang/8.0.1/bin/llvm-extract
/usr/lib64/clang/8.0.1/bin/llvm-lib
/usr/lib64/clang/8.0.1/bin/llvm-link
/usr/lib64/clang/8.0.1/bin/llvm-lto
/usr/lib64/clang/8.0.1/bin/llvm-lto2
/usr/lib64/clang/8.0.1/bin/llvm-mc
/usr/lib64/clang/8.0.1/bin/llvm-mca
/usr/lib64/clang/8.0.1/bin/llvm-modextract
/usr/lib64/clang/8.0.1/bin/llvm-mt
/usr/lib64/clang/8.0.1/bin/llvm-nm
/usr/lib64/clang/8.0.1/bin/llvm-objcopy
/usr/lib64/clang/8.0.1/bin/llvm-objdump
/usr/lib64/clang/8.0.1/bin/llvm-opt-report
/usr/lib64/clang/8.0.1/bin/llvm-pdbutil
/usr/lib64/clang/8.0.1/bin/llvm-profdata
/usr/lib64/clang/8.0.1/bin/llvm-ranlib
/usr/lib64/clang/8.0.1/bin/llvm-rc
/usr/lib64/clang/8.0.1/bin/llvm-readelf
/usr/lib64/clang/8.0.1/bin/llvm-readobj
/usr/lib64/clang/8.0.1/bin/llvm-rtdyld
/usr/lib64/clang/8.0.1/bin/llvm-size
/usr/lib64/clang/8.0.1/bin/llvm-spirv
/usr/lib64/clang/8.0.1/bin/llvm-split
/usr/lib64/clang/8.0.1/bin/llvm-stress
/usr/lib64/clang/8.0.1/bin/llvm-strings
/usr/lib64/clang/8.0.1/bin/llvm-strip
/usr/lib64/clang/8.0.1/bin/llvm-symbolizer
/usr/lib64/clang/8.0.1/bin/llvm-tblgen
/usr/lib64/clang/8.0.1/bin/llvm-undname
/usr/lib64/clang/8.0.1/bin/llvm-xray
/usr/lib64/clang/8.0.1/bin/obj2yaml
/usr/lib64/clang/8.0.1/bin/opt
/usr/lib64/clang/8.0.1/bin/sancov
/usr/lib64/clang/8.0.1/bin/sanstats
/usr/lib64/clang/8.0.1/bin/verify-uselistorder
/usr/lib64/clang/8.0.1/bin/yaml2obj

%files bin
%defattr(-,root,root,-)
/usr/bin/bugpoint-8
/usr/bin/c-index-test-8
/usr/bin/clang++-8
/usr/bin/clang-8
/usr/bin/clang-check-8
/usr/bin/clang-cl-8
/usr/bin/clang-cpp-8
/usr/bin/clang-extdef-mapping-8
/usr/bin/clang-format-8
/usr/bin/clang-import-test-8
/usr/bin/clang-offload-bundler-8
/usr/bin/clang-refactor-8
/usr/bin/clang-rename-8
/usr/bin/diagtool-8
/usr/bin/dsymutil-8
/usr/bin/git-clang-format-8
/usr/bin/hmaptool-8
/usr/bin/llc-8
/usr/bin/lli-8
/usr/bin/llvm-ar-8
/usr/bin/llvm-as-8
/usr/bin/llvm-bcanalyzer-8
/usr/bin/llvm-c-test-8
/usr/bin/llvm-cat-8
/usr/bin/llvm-cfi-verify-8
/usr/bin/llvm-config-8
/usr/bin/llvm-cov-8
/usr/bin/llvm-cvtres-8
/usr/bin/llvm-cxxdump-8
/usr/bin/llvm-cxxfilt-8
/usr/bin/llvm-cxxmap-8
/usr/bin/llvm-diff-8
/usr/bin/llvm-dis-8
/usr/bin/llvm-dlltool-8
/usr/bin/llvm-dwarfdump-8
/usr/bin/llvm-dwp-8
/usr/bin/llvm-elfabi-8
/usr/bin/llvm-exegesis-8
/usr/bin/llvm-extract-8
/usr/bin/llvm-lib-8
/usr/bin/llvm-link-8
/usr/bin/llvm-lto-8
/usr/bin/llvm-lto2-8
/usr/bin/llvm-mc-8
/usr/bin/llvm-mca-8
/usr/bin/llvm-modextract-8
/usr/bin/llvm-mt-8
/usr/bin/llvm-nm-8
/usr/bin/llvm-objcopy-8
/usr/bin/llvm-objdump-8
/usr/bin/llvm-opt-report-8
/usr/bin/llvm-pdbutil-8
/usr/bin/llvm-profdata-8
/usr/bin/llvm-ranlib-8
/usr/bin/llvm-rc-8
/usr/bin/llvm-readelf-8
/usr/bin/llvm-readobj-8
/usr/bin/llvm-rtdyld-8
/usr/bin/llvm-size-8
/usr/bin/llvm-spirv-8
/usr/bin/llvm-split-8
/usr/bin/llvm-stress-8
/usr/bin/llvm-strings-8
/usr/bin/llvm-strip-8
/usr/bin/llvm-symbolizer-8
/usr/bin/llvm-tblgen-8
/usr/bin/llvm-undname-8
/usr/bin/llvm-xray-8
/usr/bin/obj2yaml-8
/usr/bin/opt-8
/usr/bin/sancov-8
/usr/bin/sanstats-8
/usr/bin/verify-uselistorder-8
/usr/bin/yaml2obj-8

%files extras
%defattr(-,root,root,-)
/usr/lib64/LLVMgold-8.so
/usr/lib64/clang/8.0.1/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_cmath.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_device_functions.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/8.0.1/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/8.0.1/include/__stddef_max_align_t.h
/usr/lib64/clang/8.0.1/include/__wmmintrin_aes.h
/usr/lib64/clang/8.0.1/include/__wmmintrin_pclmul.h
/usr/lib64/clang/8.0.1/include/adxintrin.h
/usr/lib64/clang/8.0.1/include/altivec.h
/usr/lib64/clang/8.0.1/include/ammintrin.h
/usr/lib64/clang/8.0.1/include/arm64intr.h
/usr/lib64/clang/8.0.1/include/arm_acle.h
/usr/lib64/clang/8.0.1/include/arm_fp16.h
/usr/lib64/clang/8.0.1/include/arm_neon.h
/usr/lib64/clang/8.0.1/include/armintr.h
/usr/lib64/clang/8.0.1/include/avx2intrin.h
/usr/lib64/clang/8.0.1/include/avx512bitalgintrin.h
/usr/lib64/clang/8.0.1/include/avx512bwintrin.h
/usr/lib64/clang/8.0.1/include/avx512cdintrin.h
/usr/lib64/clang/8.0.1/include/avx512dqintrin.h
/usr/lib64/clang/8.0.1/include/avx512erintrin.h
/usr/lib64/clang/8.0.1/include/avx512fintrin.h
/usr/lib64/clang/8.0.1/include/avx512ifmaintrin.h
/usr/lib64/clang/8.0.1/include/avx512ifmavlintrin.h
/usr/lib64/clang/8.0.1/include/avx512pfintrin.h
/usr/lib64/clang/8.0.1/include/avx512vbmi2intrin.h
/usr/lib64/clang/8.0.1/include/avx512vbmiintrin.h
/usr/lib64/clang/8.0.1/include/avx512vbmivlintrin.h
/usr/lib64/clang/8.0.1/include/avx512vlbitalgintrin.h
/usr/lib64/clang/8.0.1/include/avx512vlbwintrin.h
/usr/lib64/clang/8.0.1/include/avx512vlcdintrin.h
/usr/lib64/clang/8.0.1/include/avx512vldqintrin.h
/usr/lib64/clang/8.0.1/include/avx512vlintrin.h
/usr/lib64/clang/8.0.1/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/8.0.1/include/avx512vlvnniintrin.h
/usr/lib64/clang/8.0.1/include/avx512vnniintrin.h
/usr/lib64/clang/8.0.1/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/8.0.1/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/8.0.1/include/avxintrin.h
/usr/lib64/clang/8.0.1/include/bmi2intrin.h
/usr/lib64/clang/8.0.1/include/bmiintrin.h
/usr/lib64/clang/8.0.1/include/cetintrin.h
/usr/lib64/clang/8.0.1/include/cldemoteintrin.h
/usr/lib64/clang/8.0.1/include/clflushoptintrin.h
/usr/lib64/clang/8.0.1/include/clwbintrin.h
/usr/lib64/clang/8.0.1/include/clzerointrin.h
/usr/lib64/clang/8.0.1/include/cpuid.h
/usr/lib64/clang/8.0.1/include/cuda_wrappers/algorithm
/usr/lib64/clang/8.0.1/include/cuda_wrappers/complex
/usr/lib64/clang/8.0.1/include/cuda_wrappers/new
/usr/lib64/clang/8.0.1/include/emmintrin.h
/usr/lib64/clang/8.0.1/include/f16cintrin.h
/usr/lib64/clang/8.0.1/include/float.h
/usr/lib64/clang/8.0.1/include/fma4intrin.h
/usr/lib64/clang/8.0.1/include/fmaintrin.h
/usr/lib64/clang/8.0.1/include/fxsrintrin.h
/usr/lib64/clang/8.0.1/include/gfniintrin.h
/usr/lib64/clang/8.0.1/include/htmintrin.h
/usr/lib64/clang/8.0.1/include/htmxlintrin.h
/usr/lib64/clang/8.0.1/include/ia32intrin.h
/usr/lib64/clang/8.0.1/include/immintrin.h
/usr/lib64/clang/8.0.1/include/intrin.h
/usr/lib64/clang/8.0.1/include/inttypes.h
/usr/lib64/clang/8.0.1/include/invpcidintrin.h
/usr/lib64/clang/8.0.1/include/iso646.h
/usr/lib64/clang/8.0.1/include/limits.h
/usr/lib64/clang/8.0.1/include/lwpintrin.h
/usr/lib64/clang/8.0.1/include/lzcntintrin.h
/usr/lib64/clang/8.0.1/include/mm3dnow.h
/usr/lib64/clang/8.0.1/include/mm_malloc.h
/usr/lib64/clang/8.0.1/include/mmintrin.h
/usr/lib64/clang/8.0.1/include/module.modulemap
/usr/lib64/clang/8.0.1/include/movdirintrin.h
/usr/lib64/clang/8.0.1/include/msa.h
/usr/lib64/clang/8.0.1/include/mwaitxintrin.h
/usr/lib64/clang/8.0.1/include/nmmintrin.h
/usr/lib64/clang/8.0.1/include/opencl-c.h
/usr/lib64/clang/8.0.1/include/pconfigintrin.h
/usr/lib64/clang/8.0.1/include/pkuintrin.h
/usr/lib64/clang/8.0.1/include/pmmintrin.h
/usr/lib64/clang/8.0.1/include/popcntintrin.h
/usr/lib64/clang/8.0.1/include/prfchwintrin.h
/usr/lib64/clang/8.0.1/include/ptwriteintrin.h
/usr/lib64/clang/8.0.1/include/rdseedintrin.h
/usr/lib64/clang/8.0.1/include/rtmintrin.h
/usr/lib64/clang/8.0.1/include/s390intrin.h
/usr/lib64/clang/8.0.1/include/sgxintrin.h
/usr/lib64/clang/8.0.1/include/shaintrin.h
/usr/lib64/clang/8.0.1/include/smmintrin.h
/usr/lib64/clang/8.0.1/include/stdalign.h
/usr/lib64/clang/8.0.1/include/stdarg.h
/usr/lib64/clang/8.0.1/include/stdatomic.h
/usr/lib64/clang/8.0.1/include/stdbool.h
/usr/lib64/clang/8.0.1/include/stddef.h
/usr/lib64/clang/8.0.1/include/stdint.h
/usr/lib64/clang/8.0.1/include/stdnoreturn.h
/usr/lib64/clang/8.0.1/include/tbmintrin.h
/usr/lib64/clang/8.0.1/include/tgmath.h
/usr/lib64/clang/8.0.1/include/tmmintrin.h
/usr/lib64/clang/8.0.1/include/unwind.h
/usr/lib64/clang/8.0.1/include/vadefs.h
/usr/lib64/clang/8.0.1/include/vaesintrin.h
/usr/lib64/clang/8.0.1/include/varargs.h
/usr/lib64/clang/8.0.1/include/vecintrin.h
/usr/lib64/clang/8.0.1/include/vpclmulqdqintrin.h
/usr/lib64/clang/8.0.1/include/waitpkgintrin.h
/usr/lib64/clang/8.0.1/include/wbnoinvdintrin.h
/usr/lib64/clang/8.0.1/include/wmmintrin.h
/usr/lib64/clang/8.0.1/include/x86intrin.h
/usr/lib64/clang/8.0.1/include/xmmintrin.h
/usr/lib64/clang/8.0.1/include/xopintrin.h
/usr/lib64/clang/8.0.1/include/xsavecintrin.h
/usr/lib64/clang/8.0.1/include/xsaveintrin.h
/usr/lib64/clang/8.0.1/include/xsaveoptintrin.h
/usr/lib64/clang/8.0.1/include/xsavesintrin.h
/usr/lib64/clang/8.0.1/include/xtestintrin.h

%files extras-libllvm
%defattr(-,root,root,-)
/usr/lib64/libLLVM.so.8

%files lib
%defattr(-,root,root,-)
/usr/lib/bfd-plugins/LLVMgold-8.so
/usr/lib64/libLTO.so.8
/usr/lib64/libOptRemarks.so.8
/usr/lib64/libclang.so.8
/usr/lib64/libclangARCMigrate.so.8
/usr/lib64/libclangAST.so.8
/usr/lib64/libclangASTMatchers.so.8
/usr/lib64/libclangAnalysis.so.8
/usr/lib64/libclangBasic.so.8
/usr/lib64/libclangCodeGen.so.8
/usr/lib64/libclangCrossTU.so.8
/usr/lib64/libclangDriver.so.8
/usr/lib64/libclangDynamicASTMatchers.so.8
/usr/lib64/libclangEdit.so.8
/usr/lib64/libclangFormat.so.8
/usr/lib64/libclangFrontend.so.8
/usr/lib64/libclangFrontendTool.so.8
/usr/lib64/libclangHandleCXX.so.8
/usr/lib64/libclangHandleLLVM.so.8
/usr/lib64/libclangIndex.so.8
/usr/lib64/libclangLex.so.8
/usr/lib64/libclangParse.so.8
/usr/lib64/libclangRewrite.so.8
/usr/lib64/libclangRewriteFrontend.so.8
/usr/lib64/libclangSema.so.8
/usr/lib64/libclangSerialization.so.8
/usr/lib64/libclangStaticAnalyzerCheckers.so.8
/usr/lib64/libclangStaticAnalyzerCore.so.8
/usr/lib64/libclangStaticAnalyzerFrontend.so.8
/usr/lib64/libclangTooling.so.8
/usr/lib64/libclangToolingASTDiff.so.8
/usr/lib64/libclangToolingCore.so.8
/usr/lib64/libclangToolingInclusions.so.8
/usr/lib64/libclangToolingRefactor.so.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvm8/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/llvm8/4b1bf296ce693a6396265c60a2bfc237cae9a14e
/usr/share/package-licenses/llvm8/59d395cdb2e7a9940a56014b5ab7184324ab5cd3
/usr/share/package-licenses/llvm8/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/llvm8/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/llvm8/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/llvm8/e20dfaf19593ba52e55f3fd6e34532193f594fbb
